Second problem
Agilefreaks/Test pull request #31
Opened 2018-05-03 18:47 UTC by HiciuStefan

2018-05-03 20:19 UTC, alexandru-calinoiu requested changes
Please review my comment.

2018-05-03 20:19 UTC, alexandru-calinoiu commented on second_problem.rb
> +    @min_value = -1
I don't think this is correct, integers have negative numbers smaller than -1, so for example an array of [-2, -3, -4] should return [-2, -3].

In the initial solution you have a large negative number, I wanted to know how you arrived at that number.

2018-05-03 21:03 UTC, HiciuStefan commented on second_problem.rb
> +    @min_value = -1
My ideea was to get a "big" number to have a kind of -MAXINT. That's why the -1234567890.
In this iteration i just considered positive numbers. -> bad
I've updated the code to have this -MAXINT value.

2018-05-08 05:24 UTC, alexandru-calinoiu commented on second_problem.rb
> +  MAX = 2 ** (N_BITS - 2) - 1
This makes sens :+1:

2018-05-08 05:24 UTC, alexandru-calinoiu commented
Thank you, will write a email shortly.

2018-05-08 05:24 UTC, closed without merging