Done with all three problems and unit tests for them
Agilefreaks/Test pull request #48
Opened 2019-04-21 10:02 UTC by CristinaBirsan

2019-04-21 11:22 UTC, alexandru-calinoiu requested changes
Please review my comments, we need proper unit testing before we start looking at the implementations more closely.

2019-04-21 11:22 UTC, alexandru-calinoiu commented on duplicate.js
> +unitTest.testDupl = function(method){
This is not the way unit tests are usually written in javascript, please search for a common way and adjust your implementation.

2019-04-21 14:54 UTC, CristinaBirsan commented
Trebuie sa folosesc un framework pentru unit tests?

On Sun, 21 Apr 2019 at 14:22, Calinoiu Alexandru Nicolae <
notifications@github.com> wrote:

> *@alexandru-calinoiu* requested changes on this pull request.
>
> Please review my comments, we need proper unit testing before we start
> looking at the implementations more closely.
> ------------------------------
>
> In duplicate.js
> <https://github.com/Agilefreaks/Test/pull/48#discussion_r277163675>:
>
> > @@ -0,0 +1,34 @@
> +function duplicate(arr){
> +  var a =new Set(arr);
> +  if (arr.length === a.size){
> +     return false;
> +  }
> +  else {
> +      return true;
> +  }
> +}
> +
> +var unitTest={};
> +
> +unitTest.testDupl = function(method){
>
> This is not the way unit tests are usually written in javascript, please
> search for a common way and adjust your implementation.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Agilefreaks/Test/pull/48#pullrequestreview-228908546>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AL3MAYD3Q36SZZYH52MEEF3PRRE5VANCNFSM4HHLKY4Q>
> .
>

2019-04-22 05:11 UTC, alexandru-calinoiu requested changes
Using a custom unit testing framework is a interesting solution and very unusual, it might be worth exploring this further given that it can be an overhead to add a testing framework.

The code is poorly formatted and and not following any coding conventions.
The solutions for 2 of the problems don't respect specified constrains.

2019-04-22 05:11 UTC, alexandru-calinoiu commented on suma.js
> +    sum+=arr[i];
The problem stated `Given an integer array of size N, compute the sum of all *even* numbers in this array`

Is even numbers not all numbers.

2019-04-22 05:11 UTC, alexandru-calinoiu commented on max2.js
> +  var max2 =Math.max.apply(null,arr);
This computation of max is a waste of time, as it will be overwritten later on.

You probably want to remove `max1` from the array and the compute max2.

2019-04-22 05:11 UTC, alexandru-calinoiu commented on max2.js
> +function secondMax(arr){
Even when corrected this solution is inefficient, we can suppose `Math.max` will traverse the entire array, in your current implementation this happens 3 times.

Can you come up with a solution that only traverses the array 1 time.

2019-04-22 05:11 UTC, alexandru-calinoiu commented on duplicate.js
> +  var a =new Set(arr);
Again a miss read of the problem statement `Try to work within the array without using any other temporary data structures.`

The set here ([poorly](https://blog.elpassion.com/naming-101-quick-guide-on-how-to-name-things-a9bcbfd02f02) named a) is a temporary data structure.

2019-04-22 05:43 UTC, CristinaBirsan commented on suma.js
> +    sum+=arr[i];
I will restore the code and send it as soon as possible.

2019-04-23 14:02 UTC, alexandru-calinoiu reviewed
This is an improvement over the previous implementation, left some comments there is nothing to act on now.

Will close the pr and get back to you via email.

2019-04-23 14:02 UTC, alexandru-calinoiu commented on test/duplicateTest.js
> +});
We should have unit test for other use cases also.

2019-04-23 14:02 UTC, alexandru-calinoiu commented on duplicate.js
> +        if(arr.indexOf(arr[i])!=i){
This is a improved solution indeed.

[indexOf](https://www.w3schools.com/jsref/jsref_indexof_array.asp) will search the array via an loop, this means that you will have an inner loop.

The problem stated that you should not use a inner loop.

2019-04-23 14:02 UTC, alexandru-calinoiu commented on test/twoMaxTest.js
> +    });
If you write a test with an array like `[-5, -4]` it will fail as you don't account for negative numbers

2019-04-23 14:02 UTC, alexandru-calinoiu commented on twoMax.js
> +    return v.toString();
Why return a string vs an array?

2019-04-23 14:27 UTC, closed without merging